version: '3.9'

services:
  app:
    image: app
    build:
      context: .
      args:
        - DEV = true
      dockerfile: ./Dockerfile
    volumes:
    - ./app:/app
    ports:
    - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
#     depends_on:
#     - db
#   db:
#     image: postgres:14
#     volumes:
#     - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data: